-- Esquema completo del modelo de datos (ver 08_Modelo_de_Datos_y_Arquitectura.docx),
-- en Postgres (Supabase).
-- Idempotente: se puede ejecutar varias veces (CREATE ... IF NOT EXISTS). Lo
-- aplica "npm run seed" (y por tanto "npm start"); también se puede pegar en el
-- SQL Editor de Supabase.
--
-- Tipos elegidos para que la API devuelva exactamente los mismos JSON que con
-- SQLite:
-- - Ids y cantidades en integer (pg los entrega como número de JavaScript).
-- - Precios y totales de venta en double precision (antes REAL), también número.
-- - Fechas en timestamp(0) sin zona horaria, guardadas en UTC; db.js las entrega
--   como texto "YYYY-MM-DD HH:MM:SS", igual que datetime('now') de SQLite.
-- - Banderas 0/1 en integer con CHECK, como antes (la app espera 0/1).
-- Si un sprint necesita un campo nuevo en una tabla existente, agrégalo al final
-- con ALTER TABLE ... ADD COLUMN IF NOT EXISTS (CREATE TABLE IF NOT EXISTS no altera).

-- ---------------------------------------------------------------------------
-- Modelo base (12 entidades)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre          text NOT NULL,
  usuario_login   text NOT NULL UNIQUE,
  password_hash   text NOT NULL,
  rol             text NOT NULL CHECK (rol IN ('administrador','mesero','cajero')),
  activo          integer NOT NULL DEFAULT 1,
  fecha_creacion  timestamp(0) NOT NULL DEFAULT date_trunc('second', now() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS categorias (
  id_categoria    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre          text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS productos (
  id_producto     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_categoria    integer NOT NULL REFERENCES categorias(id_categoria),
  nombre          text NOT NULL,
  unidad_medida   text NOT NULL,
  precio          double precision NOT NULL,
  stock_actual    integer NOT NULL DEFAULT 0,
  umbral_alerta   integer NOT NULL DEFAULT 0,
  -- Tasas en puntos básicos (1900 = 19 %). El precio ya incluye el impuesto.
  -- IVA aplica a la venta para llevar; INC (Art. 512-1 E.T.) al consumo en el sitio.
  tasa_iva_bps         integer NOT NULL DEFAULT 1900 CHECK (tasa_iva_bps BETWEEN 0 AND 10000),
  tasa_inc_bps         integer NOT NULL DEFAULT 0 CHECK (tasa_inc_bps BETWEEN 0 AND 10000),
  es_bebida_alcoholica integer NOT NULL DEFAULT 0 CHECK (es_bebida_alcoholica IN (0,1))
);

CREATE TABLE IF NOT EXISTS proveedores (
  id_proveedor    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre          text NOT NULL,
  contacto        text
);

CREATE TABLE IF NOT EXISTS producto_proveedor (
  id_producto     integer NOT NULL REFERENCES productos(id_producto),
  id_proveedor    integer NOT NULL REFERENCES proveedores(id_proveedor),
  PRIMARY KEY (id_producto, id_proveedor)
);

CREATE TABLE IF NOT EXISTS mesas (
  id_mesa         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero          integer NOT NULL UNIQUE,
  codigo_qr_token text NOT NULL UNIQUE,
  estado          text NOT NULL DEFAULT 'libre' CHECK (estado IN ('libre','ocupada'))
);

CREATE TABLE IF NOT EXISTS ventas (
  id_venta        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo            text NOT NULL CHECK (tipo IN ('mesa','mostrador')),
  id_mesa         integer REFERENCES mesas(id_mesa),
  id_usuario      integer NOT NULL REFERENCES usuarios(id_usuario),
  total           double precision NOT NULL DEFAULT 0,
  fecha_hora      timestamp(0) NOT NULL DEFAULT date_trunc('second', now() AT TIME ZONE 'utc'),
  -- Una venta anulada (vía su factura) no se borra; los reportes la excluyen.
  estado          text NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa','anulada'))
);

CREATE TABLE IF NOT EXISTS pedidos (
  id_pedido       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_mesa         integer NOT NULL REFERENCES mesas(id_mesa),
  id_venta        integer REFERENCES ventas(id_venta),
  estado          text NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','entregado')),
  notificado      integer NOT NULL DEFAULT 0,
  fecha_hora      timestamp(0) NOT NULL DEFAULT date_trunc('second', now() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS pedido_detalle (
  id_pedido_detalle integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido         integer NOT NULL REFERENCES pedidos(id_pedido),
  id_producto       integer NOT NULL REFERENCES productos(id_producto),
  cantidad          integer NOT NULL,
  precio_unitario   double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS venta_detalle (
  id_venta_detalle  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta          integer NOT NULL REFERENCES ventas(id_venta),
  id_pedido_detalle integer REFERENCES pedido_detalle(id_pedido_detalle),
  id_producto       integer NOT NULL REFERENCES productos(id_producto),
  cantidad          integer NOT NULL,
  precio_unitario   double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS movimientos_inventario (
  id_movimiento   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_producto     integer NOT NULL REFERENCES productos(id_producto),
  tipo            text NOT NULL CHECK (tipo IN ('entrada','salida')),
  motivo          text NOT NULL,
  cantidad        integer NOT NULL,
  id_proveedor    integer REFERENCES proveedores(id_proveedor),
  id_venta        integer REFERENCES ventas(id_venta),
  id_usuario      integer NOT NULL REFERENCES usuarios(id_usuario),
  fecha_hora      timestamp(0) NOT NULL DEFAULT date_trunc('second', now() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS log_auditoria (
  id_log          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario      integer NOT NULL REFERENCES usuarios(id_usuario),
  accion          text NOT NULL CHECK (accion IN ('crear','editar','eliminar')),
  entidad         text NOT NULL,
  id_entidad      integer NOT NULL,
  fecha_hora      timestamp(0) NOT NULL DEFAULT date_trunc('second', now() AT TIME ZONE 'utc')
);

-- ---------------------------------------------------------------------------
-- Facturación (comprobante interno de venta; aún sin integración con la DIAN)
-- ---------------------------------------------------------------------------

-- Datos del negocio que emite. Una sola fila (id = 1); cada factura guarda una
-- copia de estos datos, así que editarlos no altera facturas ya emitidas.
CREATE TABLE IF NOT EXISTS emisor (
  id                integer PRIMARY KEY CHECK (id = 1),
  razon_social      text NOT NULL,
  nit               text NOT NULL,
  dv                text NOT NULL,
  direccion         text NOT NULL,
  municipio         text NOT NULL DEFAULT 'Floridablanca',
  departamento      text NOT NULL DEFAULT 'Santander',
  telefono          text,
  regimen           text NOT NULL,
  titulo_documento  text NOT NULL DEFAULT 'Comprobante de venta',
  leyenda_pie       text NOT NULL
);

-- Consecutivo de facturación. Hoy hay una sola secuencia interna (sin prefijo
-- ni rango); los campos de resolución quedan listos para cuando exista una de
-- la DIAN. Solo una secuencia puede estar activa a la vez.
CREATE TABLE IF NOT EXISTS secuencias_factura (
  id_secuencia       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prefijo            text,
  numero_actual      integer NOT NULL DEFAULT 0,
  rango_desde        integer NOT NULL DEFAULT 1,
  rango_hasta        integer,
  resolucion_numero  text,
  resolucion_fecha   text,
  vigencia_hasta     text,
  activa             integer NOT NULL DEFAULT 1 CHECK (activa IN (0,1))
);
CREATE UNIQUE INDEX IF NOT EXISTS una_secuencia_activa ON secuencias_factura(activa) WHERE activa = 1;

-- Una factura por venta. Nunca se borra: se anula cambiando el estado.
CREATE TABLE IF NOT EXISTS facturas (
  id_factura           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_secuencia         integer NOT NULL REFERENCES secuencias_factura(id_secuencia),
  numero               integer NOT NULL,
  numero_completo      text NOT NULL,
  id_venta             integer NOT NULL UNIQUE REFERENCES ventas(id_venta),
  id_mesa              integer REFERENCES mesas(id_mesa),
  id_usuario           integer NOT NULL REFERENCES usuarios(id_usuario),
  fecha_expedicion     timestamp(0) NOT NULL DEFAULT date_trunc('second', now() AT TIME ZONE 'utc'),
  tipo_consumo         text NOT NULL CHECK (tipo_consumo IN ('en_sitio','para_llevar')),
  emisor_razon_social  text NOT NULL,
  emisor_nit           text NOT NULL,
  emisor_dv            text NOT NULL,
  emisor_direccion     text NOT NULL,
  emisor_municipio     text NOT NULL,
  emisor_departamento  text NOT NULL,
  emisor_telefono      text,
  emisor_regimen       text NOT NULL,
  titulo_documento     text NOT NULL,
  leyenda_pie          text NOT NULL,
  cliente_nombre       text NOT NULL DEFAULT 'Consumidor Final',
  cliente_tipo_doc     text CHECK (cliente_tipo_doc IN ('CC','NIT','CE','PP')),
  cliente_num_doc      text,
  cliente_dv           text,
  forma_pago           text NOT NULL CHECK (forma_pago IN ('efectivo','tarjeta_debito','tarjeta_credito','transferencia')),
  subtotal             integer NOT NULL,
  total_iva            integer NOT NULL,
  total_inc            integer NOT NULL,
  total_impuestos      integer NOT NULL,
  total                integer NOT NULL,
  estado               text NOT NULL DEFAULT 'emitida' CHECK (estado IN ('emitida','anulada')),
  motivo_anulacion     text,
  fecha_anulacion      timestamp(0),
  id_usuario_anulacion integer REFERENCES usuarios(id_usuario),
  UNIQUE (id_secuencia, numero)
);

-- Líneas de la factura con nombre, precio y tasas copiados al momento de emitir.
-- Valores en pesos enteros; tasas en puntos básicos.
CREATE TABLE IF NOT EXISTS factura_items (
  id_item          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_factura       integer NOT NULL REFERENCES facturas(id_factura) ON DELETE RESTRICT,
  id_producto      integer NOT NULL REFERENCES productos(id_producto),
  descripcion      text NOT NULL,
  cantidad         integer NOT NULL,
  precio_unitario  integer NOT NULL,
  base_linea       integer NOT NULL,
  tasa_iva_bps     integer NOT NULL,
  valor_iva        integer NOT NULL,
  tasa_inc_bps     integer NOT NULL,
  valor_inc        integer NOT NULL,
  total_linea      integer NOT NULL
);
